### PR TITLE
[WIP] Plugins Managed By Service Provider

### PR DESCRIPTION
**Pull request by Foxtrek64**
This is being added as a PR for transparency. Still a WIP, but there are a few major changes in this version:

- [x] ~~Remove NetStandard2.1, Net6, and Net7 targets.~~ Restored
- [x] `IPluginDescriptor.ConfigureServices()` is now `static virtual` and accepts an `IServiceCollection`. On versions older than NET8/C#11, the static virtual method is missing and reflection is used to find a static method in the implementation with the same name and accepting an `IServiceCollection`. If no such method exists, nothing is done.
- [x] Services are now registered via `IServiceCollection.AddPlugins()`, which scans assemblies and registers the plugins with the `IServiceProvider`
- [x] Remove abstract `PluginDescriptor`.
- [x] Rename `RemoraPlugin` -> `RemoraPluginAttribute`.
- [ ] Use CodeGen rather than reflection to register plugins in the current assembly.
- [x] Allow multiple plugins per assembly.
- [x] Instantiate plugins at runtime via `IServiceProvider`
- [x] May get rid of plugin tree. Dependency relationship may not need to be explicitly modeled with plugins managed by `IServiceProvider`.

In theory, utilization of this library should now look like this:

```cs
var pluginServiceOptions = PluginServiceOptions.Default;

var serviceCollection = new ServiceCollection()
    .AddPlugins(pluginServiceOptions);

_services = serviceCollection.BuildServiceProvider();

var pluginService = _services.GetRequiredService<PluginService>();

var initializePlugins = await pluginService.InitializePluginsAsync(ct);
if (!initializePlugins.IsSuccess)
{
    // check initializePlugins.Error to figure out why
    return;
}

var migratePlugins = await pluginService.MigratePluginsAsync(ct);
if (!migratePlugins.IsSuccess)
{
    // check migratePlugins.Error to figure out why
    return;
}
```

### CODE REVIEW

**Comment by VelvetToroyashi** [comment]
> [x] Remove NetStandard2.1, Net6, and Net7 targets.
I want to point out that I can assure you Jax would not approve of this

**Comment by Foxtrek64** [comment]
> > Use CodeGen rather than reflection to register plugins in the current assembly.
> 
> Is there any rationale behind this goal? SGen would be extra code to maintain

It shunts the responsibility of finding local plugins from the consumer to the compiler. Mostly a nice-to-have at this point, and I don't know how to do code gen so it's an opportunity for me to learn.

**Comment by Foxtrek64** [comment]
Just pushed an update. I've removed the plugin tree entirely. No longer needed as the plugins are added directly to the service provider.

I've also removed (or commented out in this push) the code which filters dependencies and sorts topologically. All dependency responsibility is now in the hands of individual plugins. If a plugin requires a particular dependency, then they need to either provide it themselves or request it from the service provider. If there is a missing dependency, this is handled by the exception thrown by `GetRequiredService()`. If a plugin wants to handle this themselves, they can accept a nullable version and provide their own logic for missing dependencies.

**Comment by Nihlus** [comment]
I've not had time to properly look this over, but the plugin tree is intended for dependency-ordered initialization, not just as a container. It's a feature I've not finished yet, so removing it outright is probably not a good idea.

**Comment by Foxtrek64** [comment]
> the plugin tree is intended for dependency-ordered initialization, not just as a container

I can restore the plugin tree, but my thinking with this change is that we don't necessarily even need any sort of dependency-ordered initialization. That is, the idea behind this change is that order no longer matters, just that dependencies are available. If a plugin requires any particular dependency, it's its own responsibility to register that dependency. Definitely willing to discuss if you had alternative plans/ideas.

As for logic pertaining to initializing and migrating plugins, this is now handled by the Plugin Service. The consumer needs only to request a plugin service from the service provider and call `InitializePluginsAsync(CancellationToken)` and `MigratePluginsAsync(CancellationToken)` in order. If plugins are migrated before initialization, the result is a no-op as the latter relies on a list of plugins successfully loaded by the former.

**Pull request closed without merging**
